# Generated by Django 5.1.7 on 2025-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="chat_id",
            field=models.PositiveIntegerField(
                default=1, verbose_name="id чата в телеграм"
            ),
            preserve_default=False,
        ),
    ]
