# Generated by Django 5.1.7 on 2025-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="chat_id",
            field=models.IntegerField(verbose_name="id чата в телеграм"),
        ),
    ]
