# Generated by Django 5.1.7 on 2025-05-13 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="название вознаграждения"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=1000, verbose_name="описнаие вознаграждения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор привички",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
        migrations.CreateModel(
            name="HabitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="дата создания привычки"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название привычки"),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=400, verbose_name="место выполнеия привычки"
                    ),
                ),
                (
                    "perform_time",
                    models.TimeField(
                        null=True, verbose_name="когда выполнять привичку"
                    ),
                ),
                (
                    "substance",
                    models.CharField(
                        max_length=2000, verbose_name="содержание привычки"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="признак приятной привычки"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("ежедневно", "ежедневно"),
                            ("каждые два дня", "каждые два дня"),
                            ("еженедельно", "еженедельно"),
                        ],
                        default="ежедневно",
                        max_length=20,
                        verbose_name="периодичность выполнения",
                    ),
                ),
                (
                    "lasting_time",
                    models.TimeField(verbose_name="длительность выполнения"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="признак публичности"
                    ),
                ),
                (
                    "pleasant_hab",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.habitmodel",
                        verbose_name="приятная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор привички",
                    ),
                ),
                (
                    "reword",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.rewordmodel",
                        verbose_name="вознаграждение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
